server:
  port: 8078

spring:
  application:
    name: xiaomibms
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiaomi?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: zjh040625
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
    password: zjh040625
    lettuce:
      pool:
        max-active: 20
        max-wait: 5000ms
        max-idle: 10
        min-idle: 3

rocketmq:
  name-server: localhost:9876
  producer:
    group: bms-producer-group
    send-message-timeout: 3000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.xiaomibms.domain.entity
  configuration:
    map-underscore-to-camel-case: true


knife4j:
  enable: true
  openapi:
    title: "小米汽车电池预警接口文档"
    description: "小米汽车电池预警大作业接口文档"
    email: ""
    concat: admin
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: 接口文档
        api-rule: package
        api-rule-resources:
          - com.example.xiaomibms


# 自定义配置
bms:
  # 预警规则扫描间隔（毫秒）
  warning-scan-interval: 60000
  # Redis缓存过期时间（秒）
  cache-expire-time: 3600

  # ShardingJDBC 配置
  #  shardingsphere:
  #    mode:
  #      type: Standalone
  #      repository:
  #        type: JDBC
  #    datasource:
  #      names: ds
  #      ds:
  #        type: com.zaxxer.hikari.HikariDataSource
  #        driver-class-name: com.mysql.cj.jdbc.Driver
  #        url: jdbc:mysql://localhost:3306/xiaomi?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  #        username: root
  #        password: zjh040625
  #    rules:
  #      sharding:
  #        tables:
  #          battery_signal:
  #            actual-data-nodes: ds.battery_signal_${0..1}
  #            table-strategy:
  #              standard:
  #                sharding-column: status
  #                sharding-algorithm-name: battery-signal-status-sharding
  #        sharding-algorithms:
  #          battery-signal-status-sharding:
  #            type: INLINE
  #            props:
  #              algorithm-expression: battery_signal_${status}
  #    props:
  #      sql-show: false